pipeline:
  name: python-harness-demo
  identifier: python_harness_demo
  projectIdentifier: Python_Harness_Demo
  orgIdentifier: default

  stages:
    - stage:
        name: Python CI
        identifier: python_ci
        description: "Build and test Python application"
        type: CI

        spec:
          cloneCodebase: true

          execution:
            steps:

              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies

                  spec:
                    shell: Sh
                    command: |
                      python --version
                      pip --version
                      pip install -r requirements.txt

              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests

                  spec:
                    shell: Sh
                    command: |
                      pytest -v