pipeline:
  identifier: Build_Ganga_dhar_python_harness_demo_1791016177306
  name: Build python-harness-demo
  orgIdentifier: default
  projectIdentifier: PythonHarnessDemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1791009970988
        repoName: Ganga-dhar/python-harness-demo
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  type: Run
                  timeout: ""
                  spec:
                    command: |-
                      set -e

                      echo "Creating Python virtual environment..."

                      python3 -m venv .venv

                      . .venv/bin/activate

                      echo "Upgrading pip..."

                      python3 -m pip install --upgrade pip

                      echo "Installing dependencies..."

                      python3 -m pip install -r requirements.txt

                      echo "Python environment ready."
              - step:
                  identifier: runlinter
                  name: run linter
                  type: Run
                  timeout: ""
                  spec:
                    command: |-
                      set -e

                      echo "Running Flake8..."

                      . .venv/bin/activate

                      flake8 . --exclude=venv,.venv

                      echo "Flake8 passed."
              - step:
                  identifier: runtests
                  name: run tests
                  type: Run
                  timeout: ""
                  spec:
                    command: |-
                      set -e

                      echo "Running Python unit tests..."

                      . .venv/bin/activate

                      pytest -v

                      echo "All tests passed."
              - step:
                  identifier: dockerbuild
                  name: Docker Build
                  type: BuildAndPushDockerRegistry
                  timeout: 20m
                  spec:
                    connectorRef: AWSConnector
                    repo: python-harness-demo
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    buildArgs: {}
              - step:
                  identifier: trivyimagescan
                  name: Trivy Container Image Scan
                  type: Run
                  timeout: 15m
                  spec:
                    shell: Sh
                    command: |-
                      set -e

                      echo "Installing Trivy..."

                      apt-get update
                      apt-get install -y wget apt-transport-https gnupg

                      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
                        | gpg --dearmor \
                        | tee /usr/share/keyrings/trivy.gpg > /dev/null

                      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
                        | tee /etc/apt/sources.list.d/trivy.list

                      apt-get update
                      apt-get install -y trivy

                      echo "Running Trivy image scan..."

                      trivy image \
                        --severity HIGH,CRITICAL \
                        --exit-code 1 \
                        --ignore-unfixed \
                        python-harness-demo:<+pipeline.sequenceId>
              - step:
                  identifier: pushtoECR
                  name: Push Docker Image to Amazon ECR
                  type: BuildAndPushECR
                  timeout: 20m
                  spec:
                    connectorRef: AWSConnector
                    region: us-east-1
                    account: "730335304128"
                    imageName: python-harness-demo
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    caching: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
